version: '2'
services:
  web:
    image: react-todo:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - .:/app/ui/
       - /app/ui/node_modules/
       - /app/ui/assets/
    ports:
      - "8080:8080"
    command: npm run serve
    links:
      - api_service
  api_service:
    image: elixir-todo:v1
    build:
      context: ../todo
    command: mix phoenix.server
    volumes:
      - ../todo:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
  db:
    image: postgres:9.5
